################################################################
####         TRex test configuration file          ####
################################################################

trex:
  hostname       : csi-trex-23
  cores          : 1
  modes          : [loopback, VM, vf_nics]

