################################################################
####         TRex configuration file          ####
################################################################

trex:
  hostname       : csi-trex-21
  cores          : 1
  modes          : [VM, loopback, vf_nics]

