################################################################
####         TRex nightly test configuration file          ####
################################################################

# Napatech setup

trex:
  hostname       : SuperBK
  cores          : 4
  astf_cores     : 1
  modes          : ['loopback']

