################################################################
####         T-Rex nightly test configuration file          ####
################################################################


### T-Rex configuration:
# hostname        - can be DNS name or IP for the TRex machine for ssh to the box
# is_dual         - should the TRex inject with -p ?
# version_path    - path to the t-rex version and executable
# cores           - how many cores should be used
# latency         - rate of latency packets injected by the TRex
# modes           - list of modes (tagging) of this setup (loopback, virtual etc.)
# 	  * loopback  - Trex works via loopback. Router and TFTP configurations may be skipped.
#     * VM        - Virtual OS (accept low CPU utilization in tests, latency can get spikes)
#     * virt_nics - NICs are virtual (VMXNET3 etc.)

### Router configuration:
# hostname       - the router hostname as apears in ______# cli prefix
# ip_address     - the router's ip that can be used to communicate with
# image          - the desired imaged wished to be loaded as the router's running config
# line_password  - router password when access via Telent
# en_password    - router password when changing to "enable" mode
# interfaces     - an array of client-server pairs, representing the interfaces configurations of the router
# configurations - an array of configurations that could possibly loaded into the router during the test. 
#                  The "clean" configuration is a mandatory configuration the router will load with to run the basic test bench

### TFTP configuration:
# hostname       - the tftp hostname
# ip_address     - the tftp's ip address
# images_path    - the tftp's relative path in which the router's images are located

### Test_misc configuration:
# expected_bw    - the "golden" bandwidth (in Gbps) results planned on receiving from the test

trex:
  hostname       : trex-dan
  cores          : 2
  modes          : [VM]

router:
  model          : 1RU
  hostname       : ASR1001_T-Rex
  ip_address     : 10.56.199.247
  image          : asr1001-universalk9.BLD_V155_1_S_XE314_THROTTLE_LATEST_20141112_090734-std.bin
  #image          : asr1001-universalk9.BLD_V155_2_S_XE315_THROTTLE_LATEST_20150121_110036-std.bin
  #image          : asr1001-universalk9.BLD_V155_2_S_XE315_THROTTLE_LATEST_20150324_100047-std.bin
  line_password  : lab
  en_password    : lab
  mgmt_interface : GigabitEthernet0/0/0
  clean_config   : /Configurations/danklei/asr1001_TRex_clean_config.cfg
  intf_masking   : 255.255.255.0
  ipv6_mask      : 64
  interfaces     :
    - client : 
        name          : GigabitEthernet0/0/1
        src_mac_addr  : 0000.0001.0000
        dest_mac_addr : 0000.0001.0000
      server : 
        name          : GigabitEthernet0/0/2
        src_mac_addr  : 0000.0001.0000
        dest_mac_addr : 0000.0001.0000
      vrf_name      : null    

tftp:
  hostname       : ats-asr-srv-1
  ip_address     : 10.56.128.23
  root_dir       : /auto/avc-devtest/
  images_path    : /images/1RU/
