deck.js Support for Asciidoc
=============================
:author: Foo Bar 
:email: <foo@bar.org>
:description: just a template file.
:revdate: 2011-12-16
:revnumber: 0.1
///////////////////////
	Themes that you can choose includes:
	web-2.0, swiss, neon, beamer
///////////////////////
:deckjs_theme: web-2.0
///////////////////////
	Transitions that you can choose includes:
	fade, horizontal-slide, vertical-slide
///////////////////////
:deckjs_transition: horizontal-slide
///////////////////////
	AsciiDoc use `source-highlight` as default highlighter.

	Styles available for pygment highlighter:
	monokai, manni, perldoc, borland, colorful, default, murphy, vs, trac,
	tango, fruity, autumn, bw, emacs, vim, pastie, friendly, native,

	Uncomment following two lines if you want to highlight your code
	with `Pygments`.
///////////////////////
//:pygments:
//:pygments_style: native
///////////////////////
	Uncomment following line if you want to scroll inside slides
	with {down,up} arrow keys.
///////////////////////
//:scrollable:
///////////////////////
	Uncomment following line if you want to link css and js file 
	from outside instead of embedding them into the output file.
///////////////////////
//:linkcss:
///////////////////////
	Uncomment following line if you want to count each incremental
	bullet as a new slide
///////////////////////
//:count_nested:

== Slide One

[incremental="true"]
 * item 1
 * item 2

== Slide Two

That's all.
