#! /bin/bash

waf=waf-2.0.21
p3=${PYTHON3:-python3}

# try Pythons which can load waf

if $p3 $waf --help &> /dev/null; then
    $p3 $waf $@

# waf can't be loaded, print the error with available Python

elif which $p3 &> /dev/null; then
    $p3 $waf $@

# no Python available

else
    echo Required Python 3
    exit 1
fi

