/*
 * Copyright (c) 2004-2021 Mellanox Technologies LTD. All rights reserved
 * Copyright (c) 2021-2021 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

#ifndef CABLE_IBDM_TYPES_H_
#define CABLE_IBDM_TYPES_H_

#define CABLE_TYPE_COPPER_PASSIVE_EQUALIZED    0xb
#define CABLE_TYPE_COPPER_UNEQUALIZED          0xa
#define CABLE_NO_SEPARABLE_CONNECTOR           0x23

#define CABLE_MIN_SUPPORT_TEMPERATURE    -40
#define CABLE_MAX_SUPPORT_TEMPERATURE    125

#define MLNX_OUI_STR        "0x2c9"
#define CABLE_MLNX_OUI      0x2c9

#endif
