#ifndef HAVE_VERBS_IBV_EXP_CQ_COMPRESSED_CQE
#define HAVE_VERBS_IBV_EXP_CQ_COMPRESSED_CQE 1
#endif /* HAVE_VERBS_IBV_EXP_CQ_COMPRESSED_CQE */

#ifndef HAVE_VERBS_MLX5_ETH_VLAN_INLINE_HEADER_SIZE
#define HAVE_VERBS_MLX5_ETH_VLAN_INLINE_HEADER_SIZE 1
#endif /* HAVE_VERBS_MLX5_ETH_VLAN_INLINE_HEADER_SIZE */

