#ifndef HAVE_IBV_DEVICE_COUNTERS_SET_SUPPORT
#define HAVE_IBV_DEVICE_COUNTERS_SET_SUPPORT
#endif

#ifndef HAVE_IBV_FLOW_DV_SUPPORT
#define HAVE_IBV_FLOW_DV_SUPPORT
#endif

#ifndef HAVE_IBV_DEVICE_COUNTERS_SET_V45
#define HAVE_IBV_DEVICE_COUNTERS_SET_V45
#endif

#ifndef HAVE_IBV_FLOW_DEVX_COUNTERS
#define HAVE_IBV_FLOW_DEVX_COUNTERS
#endif

#ifndef HAVE_IBV_MLX4_WQE_LSO_SEG
#define HAVE_IBV_MLX4_WQE_LSO_SEG
#endif


#ifdef SUPPORTED_40000baseKR4_Full
#define HAVE_SUPPORTED_40000baseKR4_Full 1
#endif

#ifdef SUPPORTED_40000baseCR4_Full
#define HAVE_SUPPORTED_40000baseCR4_Full 1
#endif

#ifdef SUPPORTED_40000baseSR4_Full
#define HAVE_SUPPORTED_40000baseSR4_Full 1
#endif

#ifdef SUPPORTED_40000baseLR4_Full
#define HAVE_SUPPORTED_40000baseLR4_Full 1
#endif

#ifdef SUPPORTED_56000baseKR4_Full
#define HAVE_SUPPORTED_56000baseKR4_Full 1
#endif

#ifdef SUPPORTED_56000baseCR4_Full
#define HAVE_SUPPORTED_56000baseCR4_Full 1
#endif

#ifdef SUPPORTED_56000baseSR4_Full
#define HAVE_SUPPORTED_56000baseSR4_Full 1
#endif

#ifdef SUPPORTED_56000baseLR4_Full
#define HAVE_SUPPORTED_56000baseLR4_Full 1
#endif


