//#ifndef HAVE_VERBS_IBV_EXP_CQ_COMPRESSED_CQE
//#define HAVE_VERBS_IBV_EXP_CQ_COMPRESSED_CQE 1
//#endif /* HAVE_VERBS_IBV_EXP_CQ_COMPRESSED_CQE */

//#ifndef HAVE_VERBS_MLX5_ETH_VLAN_INLINE_HEADER_SIZE
//#define HAVE_VERBS_MLX5_ETH_VLAN_INLINE_HEADER_SIZE 1
//#endif /* HAVE_VERBS_MLX5_ETH_VLAN_INLINE_HEADER_SIZE */

//#ifndef HAVE_VERBS_IBV_EXP_FLOW_SPEC_ACTION_DROP
//#define HAVE_VERBS_IBV_EXP_FLOW_SPEC_ACTION_DROP
//#endif

#ifndef HAVE_IBV_DEVICE_COUNTERS_SET_SUPPORT
#define HAVE_IBV_DEVICE_COUNTERS_SET_SUPPORT
#endif


//#ifndef HAVE_IBV_WQ_FLAG_RX_END_PADDING
//#define HAVE_IBV_WQ_FLAG_RX_END_PADDING
//#endif



#define HAVE_VERBS_MLX5_OPCODE_TSO
