#! /bin/bash
ARGS="$@"
echo $ARGS

if [ -z "$VALGRIND_LOC" ]; then
  export VALGRIND_EXE=valgrind
else
  export VALGRIND_LIB=$VALGRIND_LOC/lib/valgrind
  export VALGRIND_EXE=$VALGRIND_LOC/bin/valgrind
fi

if ! $VALGRIND_EXE --version; then
    echo Valgrind not found
    exit 1
fi


$VALGRIND_EXE --leak-check=full --error-exitcode=1  --show-reachable=yes ./bp-sim-64 --ut --gtest_filter=$ARGS
RESULT=$?
if [ $RESULT  -ne 0 ]; then
  echo "ERROR ...."
  exit $RESULT
fi


