#define RTE_EXEC_ENV "linuxapp"
#define RTE_EXEC_ENV_LINUXAPP 1
#define RTE_MACHINE "native"
#define RTE_ARCH "x86_64"
#define RTE_ARCH_X86_64 1
#define RTE_TOOLCHAIN "gcc"
#define RTE_TOOLCHAIN_GCC 1
#undef RTE_LIBC
#undef RTE_LIBC_NEWLIB_SRC
#undef RTE_LIBC_NEWLIB_BIN
#undef RTE_LIBC_NETINCS
#undef RTE_LIBGLOSS
#define RTE_LIBRTE_EAL 1
#define RTE_MAX_LCORE 32
#define RTE_MAX_NUMA_NODES 8
#define RTE_MAX_MEMSEG 32
#define RTE_MAX_MEMZONE 512
#define RTE_MAX_TAILQ 32
#define RTE_LOG_LEVEL 8
#define RTE_LOG_HISTORY 256
#undef RTE_LIBEAL_USE_HPET 
#undef RTE_EAL_ALLOW_INV_SOCKET_ID
#undef RTE_EAL_ALWAYS_PANIC_ON_ERROR
#define RTE_LIBRTE_EAL_LINUXAPP 1
#undef RTE_LIBRTE_EAL_BAREMETAL
#define RTE_LIBRTE_ETHER 1
#undef RTE_LIBRTE_ETHDEV_DEBUG
#define RTE_MAX_ETHPORTS 32
#undef RTE_LIBRTE_IEEE1588
#define RTE_LIBRTE_IGB_PMD 1
#undef RTE_LIBRTE_IGB_DEBUG_INIT
#undef RTE_LIBRTE_IGB_DEBUG_RX
#undef RTE_LIBRTE_IGB_DEBUG_TX
#undef RTE_LIBRTE_IGB_DEBUG_TX_FREE
#undef RTE_LIBRTE_IGB_DEBUG_DRIVER
#define RTE_LIBRTE_IXGBE_PMD 1
#undef RTE_LIBRTE_IXGBE_DEBUG_INIT
#undef RTE_LIBRTE_IXGBE_DEBUG_RX
#undef RTE_LIBRTE_IXGBE_DEBUG_TX
#undef RTE_LIBRTE_IXGBE_DEBUG_TX_FREE
#undef RTE_LIBRTE_IXGBE_DEBUG_DRIVER
#define RTE_PMD_PACKET_PREFETCH 1
#define RTE_LIBRTE_RING 1
#undef RTE_LIBRTE_RING_DEBUG
#define RTE_LIBRTE_MEMPOOL 1
#define RTE_MEMPOOL_CACHE_MAX_SIZE 512
#undef RTE_LIBRTE_MEMPOOL_DEBUG
#define RTE_LIBRTE_MBUF 1
#undef RTE_LIBRTE_MBUF_DEBUG
#define RTE_MBUF_SCATTER_GATHER 1
#define RTE_MBUF_REFCNT_ATOMIC 1
#define RTE_PKTMBUF_HEADROOM 0
#define RTE_LIBRTE_TIMER 1
#undef RTE_LIBRTE_TIMER_DEBUG
#define RTE_LIBRTE_MALLOC 1
#undef RTE_LIBRTE_MALLOC_DEBUG
#define RTE_MALLOC_MEMZONE_SIZE 11M
#define RTE_MALLOC_PER_NUMA_NODE 1
#define RTE_LIBRTE_CMDLINE 1
#define RTE_LIBRTE_HASH 1
#undef RTE_LIBRTE_HASH_DEBUG
#undef RTE_LIBRTE_HASH_USE_MEMZONE
#define RTE_LIBRTE_LPM 1
#undef RTE_LIBRTE_LPM_DEBUG
#define RTE_LIBRTE_NET 1
#define RTE_APP_TEST 1
#define RTE_APP_CHKINCS 1
#define RTE_TEST_PMD 1
#undef RTE_TEST_PMD_RECORD_CORE_CYCLES
#undef RTE_TEST_PMD_RECORD_BURST_STATS
#undef RTE_LIBRTE_GCOV
#undef RTE_INSECURE_FUNCTION_WARNING
