#!/bin/bash

INPUT_ARGS=$@

if [[ $@ =~ '--python2' ]]; then
    INPUT_ARGS=${@//--python2/}
    source find_python.sh --python2
    PYTHONPATH=external_libs/scapy-2.3.1/python2/scapy/
fi

if [[ $@ =~ '--python3' ]]; then
    INPUT_ARGS=${@//--python3/}
    source find_python.sh --python3
    PYTHONPATH=external_libs/scapy-2.3.1/python3/scapy/
fi

if [ -z "$PYTHON" ]; then
    source find_python.sh
fi

export PYTHONPATH=$PYTHONPATH:automation/trex_control_plane/nstf:nstf
$PYTHON -m trex_nstf_lib.sim -p $PWD $INPUT_ARGS
