#!/bin/bash

source find_python.sh
cd automation/regression

# Python 2
echo Python2 test
$PYTHON trex_unit_test.py --functional $@
if [ $? -eq 0 ]; then
    printf "\n$PYTHON test succeeded\n\n"
else
    printf "\n*** $PYTHON test failed\n\n"
    exit -1
fi

# Python 3
echo Python3 test
$PYTHON3 trex_unit_test.py --functional $@
if [ $? -eq 0 ]; then
    printf "\n$PYTHON3 test succeeded\n\n"
else
    printf "\n*** $PYTHON3 test failed\n\n"
    exit -1
fi


