#! /bin/bash
INPUT_ARGS=${@//[]/-} # replace bizarre minuses with normal one
EXTRA_INPUT_ARGS=""
TREX_LOGS_DIR="/var/log/trex"
EMU_LOG_PATH="$TREX_LOGS_DIR/emu_daemon_server.log"
ARCH=$(uname -m)
export LD_LIBRARY_PATH=$PWD/so/


if [[ "$ARCH" == "x86_64" ]] ; then
    mkdir -p $TREX_LOGS_DIR
    ./trex_emu/trex-emu $INPUT_ARGS &> $EMU_LOG_PATH
else 
    echo "Default package supports only x86_64. Try compiling trex-emu for your platform."
    echo "https://github.com/cisco-system-traffic-generator/trex-emu "
fi
RESULT=$?

if [[ $RESULT != 0 ]]; then
    echo "trex-emu exited with a non zero code, check \"$EMU_LOG_PATH\" for more details."
fi

exit $RESULT
