################################################################
####         TRex nightly test configuration file          ####
################################################################

# Napatech setup

trex:
  hostname       : csi-trex-41
  cores          : 10
  astf_cores     : 1
  modes          : ['loopback', 'dummy']

