#!/bin/bash
INPUT_ARGS=$@

if [[ $@ =~ '--python2' ]]; then
    INPUT_ARGS=${@//--python2/}
    source ../scripts/find_python.sh --python2
fi

if [[ $@ =~ '--python3' ]]; then
    INPUT_ARGS=${@//--python3/}
    source ../scripts/find_python.sh --python3
fi

if [ -z "$PYTHON" ]; then
    source ../scripts/find_python.sh
fi

$PYTHON cov.py $@


