#!/usr/bin/env python
# encoding: utf-8

#
# Hanoh Haim
# Cisco Systems, Inc.



import ws_main

#mandatory
top = ws_main.top
out = ws_main.out

def options(opt):
    ws_main.options(opt)


def configure(conf):
    ws_main.configure(conf)


def build(bld):
    ws_main.build(bld)


def build_info(bld):
    ws_main.build_info(bld)

def pkg(bld):
    ws_main.pkg(bld)

def release(bld):
    ws_main.release(bld)

def publish(bld):
    ws_main.publish(bld)

def publish_ext(bld):
    ws_main.publish_ext(bld)

def publish_web(bld):
    ws_main.publish_web(bld)

def release_successful(bld):
    ws_main.release_successful(bld)

def sync(bld):
    ws_main.sync(bld)

def test(bld):
    ws_main.test(bld)






